### ISSUE TITLE
openDatabase verbose logging

### ISSUE THREAD

**Issue by teroz** [olliNiinivaara/SQLiteral#1]
I love this project and I have enjoyed how easy it was to replace db_sqlite.nim. I have a tiny observation. When and error is found when preparing the passed statements to opendatabase the logger doesn't show the full sql statement that the issue is about. It just displays the actual error. Showing the passed sql statement as well would be very useful
![Screenshot from 2020-04-30 15-12-02](https://user-images.githubusercontent.com/853846/80714295-0a246780-8af5-11ea-8697-1241eb6e4ec3.png)

**Comment by olliNiinivaara** [comment]
In version 1.1.0 all statements passed to opendatabase are logged (with code -1).
If error occurs, it concerns the last statement logged.
