### ISSUE TITLE
error with Nim 2.2.0

### ISSUE THREAD

**Issue by ITwrx** [olliNiinivaara/SQLiteral#9]
My project using sqliteral compiles with Nim 2.0.8, but fails with Nim 2.2.0 with:

`/home/itwrx/.nimble/pkgs2/sqliteral-4.0.0-77991dd936ec8cc1f624fe1c6074d02b2a8bc661/sqliteral.nim(620, 57) Error: expression 'getString(row, 0)' is of type 'string' and has to be used (or discarded)`

thanks

**Comment by olliNiinivaara** [comment]
Fixed in 4.0.1
